### ISSUE TITLE
Incorrect DDL order for event triggers

### ISSUE THREAD

**Issue by soedirgo** [supabase/pgadmin4#14]
# Bug report

## To Reproduce

1. Create a directory named `repro`
2. Create docker-compose.yml
```yml
services:
  db1:
    image: supabase/postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
  db2:
    image: supabase/postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: postgres
```
3. Run the following on `db1`:
```sql
CREATE FUNCTION f() RETURNS event_trigger LANGUAGE plpgsql AS $$ BEGIN END; $$;
CREATE EVENT TRIGGER et ON DDL_COMMAND_END
    WHEN TAG IN ('CREATE EXTENSION')
    EXECUTE PROCEDURE f();
```
4. Run:
```sh
docker run --rm -it --network repro_default supabase/pgadmin-schema-diff 'postgresql://postgres:postgres@db1/postgres' 'postgresql://postgres:postgres@db2/postgres'
```
5. Run the resulting SQL on `db2`

## Expected behavior

The SQL runs successfully.
